#image: maven:3.3.9-jdk-8
variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy


maven-build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - mvn package
  only:
    refs:
      - dev
  tags:
    - caseResolution
    - kmdev
  artifacts:
    paths:
      - target/CaseResolutionMVC_TECZ1908.war

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests......"
  only:
    refs:
      - dev
  tags:
    - caseResolution
    - kmdev


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - cd target
    - cp CaseResolutionMVC_TECZ1908.war /opt/setup/apache-tomcat-9.0.17/webapps/
  only:
    refs:
      - dev
  tags:
    - caseResolution
    - kmdev
